# Path to your oh-my-zsh configuration.
ZSH=~/oh-my-zsh 
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git go sudo extract)

source $ZSH/oh-my-zsh.sh

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export PATH=$PATH:~/.gem/ruby/2.1.0/bin
export EDITOR="vim"

export GOPATH="$HOME/gopath"
export GOROOT="/usr/local/opt/go/libexec/"

export PATH=$PATH:/opt/android-sdk/tools:$GOPATH/bin:$GOROOT/bin:~/.cabal/bin

# set tmux to 256color
alias tmux='TERM=xterm-256color tmux -2'

# Customize to your needs...
# my theme

eval my_orange='$FG[214]'

function prompt_char {
	if [ $UID -eq 0 ]; then echo "#"; else echo ">"; fi
}

PROMPT='
%(!.%{$fg_bold[red]%}.%{$fg_bold[red]%}%(?..[%?] )%{$fg_bold[green]%}%n%{$fg_bold[green]%}@)%m %{$fg_bold[blue]%}%(!.%1~.%~) %{$fg_bold[yellow]%}$(git_prompt_info)%{$fg_bold[blue]%}%_$(prompt_char)%{$reset_color%} '

ZSH_THEME_GIT_PROMPT_PREFIX="("
ZSH_THEME_GIT_PROMPT_SUFFIX=") "
ZSH_THEME_GIT_PROMPT_DIRTY="$my_orange *%{$fg_bold[yellow]%}"
ulimit -n 1024
